"use client";

import {
  Bath,
  Syringe,
  Moon,
  Salad,
  Cake,
  HeartCrack,
  Shield,
  Heart,
  Clapperboard,
  Zap,
  Lock,
  Star,
  Check,
  X,
  Gift,
  PartyPopper,
  Film,
  Send,
  MessageSquare,
  Headphones,
  Scissors,
  Sparkles,
  Clock,
  Wand2,
  ArrowRight,
  ArrowLeft,
  CheckCircle2,
  Plus,
  Play,
  ShieldCheck,
  Users,
  Circle,
  Quote,
  RefreshCw,
  FileText,
  BadgeCheck,
} from "lucide-react";

export const Icons = {
  bath: Bath,
  syringe: Syringe,
  moon: Moon,
  salad: Salad,
  cake: Cake,
  heartCrack: HeartCrack,
  shield: Shield,
  heart: Heart,
  clapperboard: Clapperboard,
  zap: Zap,
  lock: Lock,
  star: Star,
  check: Check,
  x: X,
  gift: Gift,
  party: PartyPopper,
  film: Film,
  send: Send,
  message: MessageSquare,
  headphones: Headphones,
  scissors: Scissors,
  sparkles: Sparkles,
  clock: Clock,
  wand: Wand2,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  checkCircle: CheckCircle2,
  plus: Plus,
  play: Play,
  shieldCheck: ShieldCheck,
  users: Users,
  circle: Circle,
  quote: Quote,
  refresh: RefreshCw,
  fileText: FileText,
  badge: BadgeCheck,
};

export type IconName = keyof typeof Icons;
